import type { Metadata } from "next";
import "./globals.css";
import { neoSansArabic } from "@/lib/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl" className="scroll-smooth">
      <body className={`${neoSansArabic.className} antialiased`}>
        <div className="container mx-auto">{children}</div>
      </body>
    </html>
  );
}
